### ISSUE TITLE
PHP gRPC extension breaks use of `--parallel`

### ISSUE THREAD

**Issue by mbomb007** [PHPCSStandards/PHP_CodeSniffer#294] opened 2024-01-19 16:01 UTC
## Describe the bug

See https://github.com/grpc/grpc/issues/20250

### To reproduce
1. Add the grpc PHP extension
2. 
```
test=$(php -r "echo ini_get('grpc.enable_fork_support');")
echo "grpc.enable_fork_support: $test"
test=$(php -r "echo ini_get('grpc.poll_strategy');")
echo "grpc.poll_strategy: $test"
```
The defaults are
```
grpc.enable_fork_support = 0
grpc.poll_strategy = 
```
3. Run PHPCS using `--parallel=2`. It will hang.

## Expected behavior

It would be helpful if src/Runner.php would check if the extension exists and either

```
ini_set('grpc.enable_fork_support', true);
ini_set('grpc.poll_strategy', 'epoll1');
```

Or, if it detects that fork support is disabled, emit a warning and set `--parallel=1`.

## Versions (please complete the following information)

| | |
|-|-|
| Operating System | [Docker `wodby/drupal-php:8.3-dev-4.52.0`]
| PHP version | [8.3]
| PHP_CodeSniffer version | [3.8.1]
| Standard | [Drupal,DrupalPractice]
| Install type | [Composer]

## Additional context

Related: https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/10

Parent issue: https://github.com/wodby/drupal-php/issues/102

## Please confirm:

- [x] I have searched the issue list and am not opening a duplicate issue.
- [x] I confirm that this bug is a bug in PHP_CodeSniffer and not in one of the external standards.
- [x] I have verified the issue still exists in the `master` branch of PHP_CodeSniffer.

**Comment by jrfnl** [comment] 2024-01-19 16:38
Tagging this ticket with "Help wanted" as I cannot triage/test this, nor validate a fix (parallel is not supported on Windows).

**Comment by jrfnl** [comment] 2024-01-19 17:37
@mbomb007 I don't think that fix suggestion is correct as `ini_get()` will return `false` if the configuration option doesn't exist and I suspect it will not exist in the majority of cases, as gRPC is a PECL extension which will only be installed by a limited set of people.

**Comment by jrfnl** [comment] 2024-01-20 12:33
@mbomb007 I'd like to see at least one other person confirming the issue + confirmation of the fix; or alternatively proof of the issue via a test, which could also safeguard the fix.

Regarding the fix itself, please use more exact checks, i.e. not `!ini_get('grpc.enable_fork_support')`, but something like `ini_get('grpc.enable_fork_support') !== '1'`.

As the fix would need to go in the `Runner` class, this might be a good reason to prioritize end-to-end tests (see #147).

For reference for others coming across this issue:
* https://github.com/grpc/grpc/issues/20250
* https://grpc.github.io/grpc/php/md_src_php__r_e_a_d_m_e.html
* https://pecl.php.net/package/grpc
* https://grpc.io/docs/languages/php/

Also, while trying to find out whether these ini settings are `PHP_INI_SYSTEM`, `PHP_INI_PERDIR`, `PHP_INI_USER` or `PHP_INI_ALL`, I came across the following issues about gRPC and forked processes which look loosely related:
* https://github.com/grpc/grpc/issues/13412
* https://github.com/grpc/grpc/issues/31772



`

**Comment by dingo-d** [comment] 2024-01-22 08:53
I've installed the grpc extension via pecl on my mac machine, and can confirm that when you run the phpcs with `parallel` option it stalls.

So I went and checked what could be stalling so I played with verbosity flags, and `-v` gave me:

```bash
phpcs --standard=psr12 --parallel=2 src -v

Registering sniffs in the PSR12 standard... DONE (60 sniffs registered)
Creating file list... DONE (3 files in queue)
```

And stalled.

But running either with `-vv` or `-vvv` worked. Not sure if those flags are maybe disregarding the `parallel` option 🤷🏼‍♂️

**Comment by tscni** [comment] 2024-01-22 15:43
Personally I'd consider setting the required grpc-INI settings a responsibility of the user, if they want to use ext-grpc together with ext-pcntl.
Instead of having every PHP tool with fork based parallelism deal with this, shouldn't it rather be on ext-grpc to highlight this issue more strongly or change the defaults? (but ultimately I suppose it's a way to avoid unnecessary support requests)

Anyway, here's an example of how Psalm deals with it by disabling ext-grpc and restarting the process with the help of `composer/xdebug-handler`: https://github.com/vimeo/psalm/blob/541bf51a2534a00d8bba5a6b76542f0c5a84a33d/src/Psalm/Internal/Cli/Psalm.php#L879-L890

**Comment by jrfnl** [comment] 2024-01-23 17:22
@mbomb007 Thanks for the update. In that case, I suggest closing this ticket.

I did some digging and over the years, there have been a handful of issues reported which alluded to the use of gRPC being problematic.
However, there has always been a working solution available, which is running PHPCS like so:
```bash
phpcs -d grpc.enable_fork_support=1 -d grpc.poll_strategy=epoll1 ...other options...
```
Or not using the `parallel` option when gRPC is loaded.

A handful or reports in relation to a broken PHP extension is not a good justification for adding a "fix"/work-around in PHPCS itself. Especially if there are other workable solutions available.

If there would be more frequent reports of this being an issue, adding the work-around could be revisited, but I maintain that preferably the issue should be fixed in gRPC itself.

For the record/future reference, these are the older issues I could find:
* https://github.com/squizlabs/PHP_CodeSniffer/issues/2767 - this is basically your issue as the OP was also using the Drupal Docker container.
* https://github.com/squizlabs/PHP_CodeSniffer/issues/2983
* https://github.com/squizlabs/PHP_CodeSniffer/issues/3518

I also came across some other external references. I will update the link in [my previous comment](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/294#issuecomment-1902083316) to add them so those lists are more complete.

**Closed** 2024-01-23 17:40 UTC
Labels: Status: wontfix

**Comment by danepowell** [comment] 2024-04-11 16:52
I certainly don't expect PHPCS to fix gRPC, but given that you _know_ this is causing users pain, I think a simple check and warning would be very kind and appreciated.

I'm so lucky to have stumbled across this issue. PHPCS started stalling out today for no reason I could think of, and it was only after digging through months of GitHub issues that I saw gRPC in the title of this one and the lightbulb clicked: I had installed gRPC as a requirement for an unrelated project.

I could have spent _hours_ on this and possibly never resolved it at all without this discovery.

**Comment by danepowell** [comment] 2024-04-11 16:58
Oh wow. I just discovered this is actually the _second_ time I've been bitten by this bug and I didn't even remember. Here's the same PHPCS issue I posted 5 years ago: https://github.com/squizlabs/PHP_CodeSniffer/issues/2767

**Comment by derrabus** [comment] 2025-02-12 11:02
Hello. I'd like to weigh in on this issue because I've lost a couple of hours of my life on it.

I'd like to introduce PHPCS to a project that uses the GRPC extension and PHPCS just hangs without any output whatsoever. It was by trail and error that I found out that disabling the GRPC extension fixes the problem.

I understand that the root cause of the problem is to be found in the GRPC extension itself. But browsing through the discussions on their tracker, I'm not very confident that this will ever happen. The issue has been present and known for almost a decade.

I also understand that we want to avoid making the PHPCS repo a collection of workarounds for broken PHP extensions, but given that the problem likely won't be solved upstream and given that it is easily detectable before running into it, can we maybe find a nice user-friendly way forward?

**Comment by jrfnl** [comment] 2025-02-12 14:14
@derrabus I'm open to suggestions with the above mentioned caveats.

One thing I have in mind for the future (but isn't my current priority, so it may well be a while before the feature exists) is to add a `--diagnose` option which would check various hard and soft system requirements and report on those.
I have some notes on this locally, but no definitive design for it yet.

I can also imagine just adding a plain warning in the requirements check (as part of #530).

Loosely related issues:
* #10
* #419, which was fixed via #447
* #530

**Comment by jrfnl** [comment] 2025-02-12 14:22
@derrabus Thinking in the context of a warning, I'd also love to hear your thoughts on the proposal in https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/184#issuecomment-2644329771 and my extra question regarding runtime system warnings/notices etc in https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/184#issuecomment-2650079347

**Comment by derrabus** [comment] 2025-02-12 14:34
> [@derrabus](https://github.com/derrabus) I'm open to suggestions with the above mentioned caveats.

My favorite solution would be disabling parallel execution and displaying a small warning on why we did that. Would that be feasible?

**Comment by jrfnl** [comment] 2025-02-12 14:58
> > [@derrabus](https://github.com/derrabus) I'm open to suggestions with the above mentioned caveats.
> 
> My favorite solution would be disabling parallel execution and displaying a small warning on why we did that. Would that be feasible?

@derrabus That has been discussed above already and rejected.

**Comment by derrabus** [comment] 2025-02-12 16:47
> [@derrabus](https://github.com/derrabus) That has been discussed above already and rejected.

Maybe I missed something, but I did not find any reason other than that the issue hasn't been reported frequently enough. I find the approach of disabling parallel execution reasonable, given that this is also the behavior when PCNTL is not available. So why not do the same if we detect that PCNTL is broken?

**Comment by jrfnl** [comment] 2025-02-12 17:33
> Maybe I missed something....

From https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/294#issuecomment-1904447738:

> PHPCS checking for function_exists('pcntl_fork') is valid as that is functionality PHPCS itself will call.
This is different from checking for the gRPC extension and gRPC ini settings, as PHPCS does not use that functionality at all.

**Comment by derrabus** [comment] 2025-02-12 18:11
I'm going to assume that quote is meant to answer the question I've ended my previous comment with.

> PHPCS checking for function_exists('pcntl_fork') is valid as that is functionality PHPCS itself will call.

Yes, it's a valid way of checking if PCNTL is available.

> This is different from checking for the gRPC extension and gRPC ini settings, as PHPCS does not use that functionality at all.

Yes, that is different. Because that check attempts to find out if a call to PCNTL will actually _work_. Right now, we could easily prevent a call that would 100% cause the PHPCS process to hang without any feedback. It's not the fault of PHPCS that this happens, but we could do something that helps people to not run into a trap.

**Comment by jrfnl** [comment] 2025-02-12 20:16
@derrabus That's the same argument which has been discussed above already. It's not a PHPCS bug, but a bug in gRPC and should be solved there. Adding a work-around in PHPCS for a bug in a unrelated tool which is not being used by PHPCS is not the way and would open the door to all sorts of nonsense "fixes" for system configuration issues outside of the control of PHPCS.

**Comment by jrfnl** [comment] 2025-02-17 08:34
@derrabus As I said before, I'm [open to suggestions](https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/294#issuecomment-2653832739), but not to rehashing the discussion which was already had above.

If you can think of something which would help or have thoughts about the other suggestions I left in my initial response to you, I'd definitely like to hear them.

**Comment by derrabus** [comment] 2025-02-17 08:57
I didn't participate in that discussion back then and found that the arguments back then hadn't been invalidated. The new argument that I could bring to the table is the time that has passed since the original discussion.

I contribute to projects that I care about. GRPC is a project that I don't care much about and tbh it looks like they don't care much about the PHP ecosystem either. A fix in GRPC hasn't happened for years and I personally doubt that it ever will. However, people might be stuck with this extension, especially if they need to operate on Google's cloud infrastructure.

PHPCS is a project I do care about. I want this tool to succeed, I want people to use it. Seeing it fail in certain environments _without any feedback_ whatsoever pains me. Especially when the agreed resolution is to fingerpoint at a badly maintained PHP extension. If we want to give helpful feedback to the user, there's no way around making PHPCS aware of that extension in one way or another.
